### ISSUE TITLE
Show changes in throughput

### ISSUE THREAD

**Issue by ggriffiniii** [bheisler/criterion.rs#241]
When defining a benchmark with a throughput and comparing runs using --baseline I get results like the following:
```
bench_small_input/decode_slice/50                                                                             
                        time:   [26.444 ns 26.454 ns 26.466 ns]
                        thrpt:  [1.7595 GiB/s 1.7602 GiB/s 1.7609 GiB/s]
                        change: [-26.246% -26.182% -26.119%] (p = 0.00 < 0.05)
                        Performance has improved.
```

It displays the time of the current iterations, throughput of current iterations, and how the time compares to the baseline. This is tremendously useful, but it would be nice to show how the throughput changed compared to the baseline. You can derive the throughput from the above, but it's not the most intuitive. Some people that are thinking about their benchmark results in terms of throughput may even see the change of 26% and assume the throughput went up by 26% when in fact it went up by 35%.

I'm open to trying to implement the change and sending a PR, but I would like to have a consensus before I start. If you agree this would be worthwhile, do you have an opinion on how the text output above should look?

maybe
```
bench_small_input/decode_slice/50                                                                             
                        time:   [26.444 ns 26.454 ns 26.466 ns]
                        thrpt:  [1.7595 GiB/s 1.7602 GiB/s 1.7609 GiB/s]
                 change:
                        time:  [-26.246% -26.182% -26.119%] (p = 0.00 < 0.05)
                        thrpt: [+35.xxx% +35.xxx% +35.xxx%] (p - 0.00 < 0.05)
                        Performance has improved.
```

It probably makes sense to also add the information to the html reports. Again, I would be happy to take a stab at it if you have an idea how you would like the data presented.
