### ISSUE TITLE
Travis CI: allow MINIMAL_VERSIONS build to fail

### ISSUE THREAD

**Issue by vpetrigo** [bheisler/criterion.rs#273]
Hello,

As `minimal-versions` is the nightly Rust feature, maybe it is worth adding that config to `allow_failures` in the Travis CI config? I mean that:

```
allow_failures:
    - os: linux
      env: MINIMAL_VERSIONS=yes
      rust: nightly
```
