### ISSUE TITLE
The readme of version 0.3 on crates.io instructs to install version 0.2 

### ISSUE THREAD

**Issue by lovasoa** [bheisler/criterion.rs#358]
The README of criterion 0.3.0 (the latest version) on crates.io indicates : 

> To start with Criterion.rs, add the following to your Cargo.toml file:
```toml
[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
```

It wondered why the documentation did not match the observed behavior of criterion for a long time before I realized I was using criterion 0.2 and not 0.3.

I see that the readme was updated on github. Could you please publish a version 0.3.0 on crates.io reflecting this change ?
