### ISSUE TITLE
I[Idea/Question] Cross-compile a bench test to run on a remote target?

### ISSUE THREAD

**Issue by RaulTrombin** [bheisler/criterion.rs#736]
I'm using criterion to run bench on a raspberry pi4 target, but compile it from zero there takes 21 minutes.
Someone already tryed to cross compile the required stuff and then execute from the target?

**Comment by steckes** [comment]
Hey!
Yes I just did it, so I will explain you how:
1. I use [cross](https://github.com/cross-rs/cross) to cross compile the project.
2. For Raspberry Pi I compile the benchmark with 
```bash
cross bench --target aarch64-unknown-linux-gnu
```
3. The benchmark will run now in the docker container, so ignore the printed results. But the benchmark will print which binary it runs, for me it looks like this
```bash
/target/aarch64-unknown-linux-gnu/release/deps/my_bench-7dfs8993ds789 --bench
```

4. now copy the binary on your raspberry pi eg. with scp
```bash
scp /target/aarch64-unknown-linux-gnu/release/deps/my_bench-7dfs8993ds789 pi@<ip_address>:/home/pi/my_bench
```

5. ssh onto the pi and run the benchmark
```bench
./my_bench --bench
```

(You could also specify the target CPU to eventually speed things up, just put before cross bench ...: `RUSTFLAGS='-C target-cpu=cortex-a72'`)

**Comment by RaulTrombin** [comment]
@stexa thks! Will try this on my runners, 
I also found a `--no-run` option for cargo bench docs, will try mix both and see if it works.

**Comment by RaulTrombin** [comment]
Thanks @steckes, 
Added option to use [bench](https://github.com/houseabsolute/actions-rust-cross/pull/32
) on action-rust-cross,

which now allow us to:
```
  cross-compile-bench:
      needs: build
      if: ${{ github.repository_owner == 'bluerobotics' }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          TARGET: [armv7-unknown-linux-gnueabihf]
      steps:
      - uses: actions/checkout@master
      - name: Cross-compile benchmark
        uses: houseabsolute/actions-rust-cross@v0.0.17
        with:
          command: bench
          target: ${{ matrix.TARGET }}
          args: "--no-run"
      - name: Upload benchmark binary
        uses: actions/upload-artifact@v4.4.3
        with:
          name: benchmark-binary
          path: target/${{ matrix.TARGET }}/release/deps/bench-*
          retention-days: 1

  run-bench:
    needs: cross-compile-bench
    runs-on: raspbian-armv7-kernel-5.10.33
    steps:
    - uses: actions/checkout@master
    - name: Download benchmark binary
      uses: actions/download-artifact@v4.1.8
      with:
        name: benchmark-binary
        path: ./bench-binary
    - name: Make benchmark executable
      run: |
        chmod +x ./bench-binary/*
    - name: Run benchmark
      run: |
        BENCH_BINARY=$(find ./bench-binary -type f -executable -name "bench-*" -not -name "*.d" | head -n 1)
        "$BENCH_BINARY" --bench --output-format bencher | tee output.txt || { echo "Basic benchmark failed"; exit 1; }
```

New benchmarking whole process reduces from 25 min to just 7 minutes.
